#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Aug 31, 2020 11:42:18 AM IST  platform: Windows NT

import sys
from db_connect import MySQL
from tkinter import messagebox as tkMessageBox
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk
import mysql.connector
from mysql.connector import Error
try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import placement_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    placement_support.set_Tk_var()
    top = Toplevel1 (root)
    placement_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    placement_support.set_Tk_var()
    top = Toplevel1 (w)
    placement_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def maleselect(self):
        self.sex='M'
    def femaleselect(self):
        self.sex='F'
    def showstudent(self):
        try:
            tkMessageBox.showinfo('Fetching student info', "Fetching student details")
            self.Listbox1.delete(0,self.Listbox1.size())
            sql_select_Query = "select * from student"
            cursor = self.mysql.cursor()
            cursor.execute(sql_select_Query)
            records = cursor.fetchall()
            for i in range(0, cursor.rowcount):
                self.Listbox1.insert(i, records[i])
        except Exception:
            tkMessageBox.showerror('Error','Error in fetching result from DB')
    def showcompany(self):
        try:
            tkMessageBox.showinfo('Fetching company info', "Fetching company details")
            self.Listbox1.delete(0,self.Listbox1.size())
            sql_select_Query = "select * from company"
            cursor = self.mysql.cursor()
            cursor.execute(sql_select_Query)
            records = cursor.fetchall()
            for i in range(0, cursor.rowcount):
                self.Listbox1.insert(i, records[i])
        except Exception:
            tkMessageBox.showerror('Error','Error in fetching result from DB')
    def showplace(self):
        company_name = self.Text6.get('1.0','end')
        try:
            tkMessageBox.showinfo('Fetching placed info', "Fetching placed student details")
            self.Listbox1.delete(0,self.Listbox1.size())
            sql_select_Query = "select * from student where placedin = '"+company_name+"'"
            cursor = self.mysql.cursor()
            cursor.execute(sql_select_Query)
            records = cursor.fetchall()
            for i in range(0, cursor.rowcount):
                self.Listbox1.insert(i, records[i])
        except Exception:
            tkMessageBox.showerror('Error','Error in fetching result from DB')

    def deletestudent(self):
        rollno = self.Text1.get('1.0','end-1c')
        cursor = self.mysql.cursor()
        try:
            cursor.execute("delete from student where rollno="+rollno)
            self.mysql.commit()
            tkMessageBox.showinfo('Deleting student info', "The student was deleted successfully")
        except Exception:
            tkMessageBox.showerror('Error in deleting', 'Error in deleting student from DB')

    def updatestuplace(self):
        rollno = self.Text1.get('1.0','end-1c')
        placedin = self.Text5.get('1.0', 'end')
        cursor = self.mysql.cursor()
        try:
            # cursor.execute("SET foreign_key_checks = 0")
            cursor.execute("update student SET placedin='"+placedin+"' where rollno="+rollno)
            self.mysql.commit()
            # cursor.execute("SET foreign_key_checks = 1")
            tkMessageBox.showinfo('modifying student info', "The student placed company modified successfully")
        except Exception:
            tkMessageBox.showerror('Error in modifying', 'Error in modifying student placed company: Integrity constraint violation')
    def updatestuinfo(self):
        rollno = self.Text1.get('1.0','end-1c')
        phone = self.Text4.get('1.0', 'end')
        cursor = self.mysql.cursor()
        try:
            cursor.execute("update student SET phone="+phone+" where rollno="+rollno)
            self.mysql.commit()
            tkMessageBox.showinfo('modifying student info', "The student mobile no modified successfully")
        except Exception:
            tkMessageBox.showerror('Error in modifying', 'Error in student info')
    def addstudent(self):
        rollno = self.Text1.get('1.0','end')
        fname = self.Text2.get('1.0','end')
        lname = self.Text3.get('1.0','end')
        sex = self.sex
        phone = self.Text4.get('1.0','end')
        placedin = self.Text5.get('1.0','end')
        try:
            mySql_insert_query = "insert into student (rollno, fname, lname, sex, phone, placedin) values ("+rollno+",'"+fname+"','"+lname+"','"+sex+"',"+phone+",'"+placedin+"')"
        
            cursor = self.mysql.cursor()
            cursor.execute(mySql_insert_query)
            self.mysql.commit()
            tkMessageBox.showinfo('Adding student info',"The student with name "+fname+" added successfully")
        except Exception:
            tkMessageBox.showerror('Error in adding','Error in adding student to DB')
    def addcompany(self):
        company_name = self.Text6.get('1.0','end')
        location = self.Text7.get('1.0','end')
        package = self.Text8.get('1.0','end')
        try:
            mySql_insert_query = "insert into company (company_name, location, package) values ('"+company_name+"','"+location+"',"+package+")"
            cursor = self.mysql.cursor()
            cursor.execute(mySql_insert_query)
            self.mysql.commit()
            tkMessageBox.showinfo('Adding company info',"The company with name "+company_name+" added successfully")
        except Exception:
            tkMessageBox.showerror('Error in adding','Error in adding company to DB')
    def __init__(self, top=None):
        try:
            self.mysql = mysql.connector.connect(host='localhost',
                                                 database='placement',
                                                 user='root',
                                                 password='sql@123')
        except Exception:
            tkMessageBox.showerror('Error','Error while connecting to MySQL DB')
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {Segoe UI} -size 9 -weight bold -underline 1"  \
            ""
        font9 = "-family {Segoe UI} -size 9 -weight bold"

        top.geometry("591x683+375+5")
        top.minsize(120, 1)
        top.maxsize(2736, 749)
        top.resizable(1, 1)
        top.title("placement")
        top.configure(background="#d9d9d9")

        self.var=tk.IntVar()
        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.034, rely=0.015, relheight=0.381
                , relwidth=0.922)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.404, rely=0.038, height=20, width=85)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font10)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Student Details''')

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.147, rely=0.146, height=21, width=64)
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Roll No.''')

        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(relx=0.147, rely=0.258, height=21, width=74)
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''First Name''')

        self.Label4 = tk.Label(self.Frame1)
        self.Label4.place(relx=0.147, rely=0.369, height=20, width=74)
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(text='''Last Name''')

        self.Label5 = tk.Label(self.Frame1)
        self.Label5.place(relx=0.128, rely=0.519, height=20, width=74)
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(text='''Gender''')

        self.Label6 = tk.Label(self.Frame1)
        self.Label6.place(relx=0.147, rely=0.631, height=20, width=74)
        self.Label6.configure(background="#d9d9d9")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(text='''Mobile No.''')

        self.Label7 = tk.Label(self.Frame1)
        self.Label7.place(relx=0.147, rely=0.742, height=20, width=64)
        self.Label7.configure(background="#d9d9d9")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(text='''Placed In''')

        self.Text1 = tk.Text(self.Frame1)
        self.Text1.place(relx=0.33, rely=0.146, relheight=0.092, relwidth=0.466)
        self.Text1.configure(background="white")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(foreground="black")
        self.Text1.configure(highlightbackground="#d9d9d9")
        self.Text1.configure(highlightcolor="black")
        self.Text1.configure(insertbackground="black")
        self.Text1.configure(selectbackground="blue")
        self.Text1.configure(selectforeground="white")
        self.Text1.configure(wrap="word")

        self.Text2 = tk.Text(self.Frame1)
        self.Text2.place(relx=0.33, rely=0.258, relheight=0.088, relwidth=0.466)
        self.Text2.configure(background="white")
        self.Text2.configure(font="TkTextFont")
        self.Text2.configure(foreground="black")
        self.Text2.configure(highlightbackground="#d9d9d9")
        self.Text2.configure(highlightcolor="black")
        self.Text2.configure(insertbackground="black")
        self.Text2.configure(selectbackground="blue")
        self.Text2.configure(selectforeground="white")
        self.Text2.configure(wrap="word")

        self.Text3 = tk.Text(self.Frame1)
        self.Text3.place(relx=0.33, rely=0.369, relheight=0.088, relwidth=0.466)
        self.Text3.configure(background="white")
        self.Text3.configure(font="TkTextFont")
        self.Text3.configure(foreground="black")
        self.Text3.configure(highlightbackground="#d9d9d9")
        self.Text3.configure(highlightcolor="black")
        self.Text3.configure(insertbackground="black")
        self.Text3.configure(selectbackground="blue")
        self.Text3.configure(selectforeground="white")
        self.Text3.configure(wrap="word")

        self.Text4 = tk.Text(self.Frame1)
        self.Text4.place(relx=0.33, rely=0.631, relheight=0.088, relwidth=0.466)
        self.Text4.configure(background="white")
        self.Text4.configure(font="TkTextFont")
        self.Text4.configure(foreground="black")
        self.Text4.configure(highlightbackground="#d9d9d9")
        self.Text4.configure(highlightcolor="black")
        self.Text4.configure(insertbackground="black")
        self.Text4.configure(selectbackground="blue")
        self.Text4.configure(selectforeground="white")
        self.Text4.configure(wrap="word")

        self.Text5 = tk.Text(self.Frame1)
        self.Text5.place(relx=0.33, rely=0.742, relheight=0.088, relwidth=0.466)
        self.Text5.configure(background="white")
        self.Text5.configure(font="TkTextFont")
        self.Text5.configure(foreground="black")
        self.Text5.configure(highlightbackground="#d9d9d9")
        self.Text5.configure(highlightcolor="black")
        self.Text5.configure(insertbackground="black")
        self.Text5.configure(selectbackground="blue")
        self.Text5.configure(selectforeground="white")
        self.Text5.configure(wrap="word")

        self.Frame3 = tk.Frame(self.Frame1)
        self.Frame3.place(relx=0.33, rely=0.481, relheight=0.131, relwidth=0.468)

        self.Frame3.configure(relief='groove')
        self.Frame3.configure(borderwidth="2")
        self.Frame3.configure(relief="groove")
        self.Frame3.configure(background="#d9d9d9")

        self.Radiobutton1 = tk.Radiobutton(self.Frame3)
        self.Radiobutton1.place(relx=0.118, rely=0.294, relheight=0.588
                , relwidth=0.306)
        self.Radiobutton1.configure(activebackground="#ececec")
        self.Radiobutton1.configure(activeforeground="#000000")
        self.Radiobutton1.configure(background="#d9d9d9")
        self.Radiobutton1.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1.configure(foreground="#000000")
        self.Radiobutton1.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1.configure(highlightcolor="black")
        self.Radiobutton1.configure(justify='left')
        self.Radiobutton1.configure(text='''Male''')
        self.Radiobutton1.configure(variable=placement_support.selectedButton)
        self.Radiobutton1.configure(variable=self.var,value=1,command=self.maleselect)

        self.Radiobutton2 = tk.Radiobutton(self.Frame3)
        self.Radiobutton2.place(relx=0.549, rely=0.294, relheight=0.588
                , relwidth=0.306)
        self.Radiobutton2.configure(activebackground="#ececec")
        self.Radiobutton2.configure(activeforeground="#000000")
        self.Radiobutton2.configure(background="#d9d9d9")
        self.Radiobutton2.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2.configure(foreground="#000000")
        self.Radiobutton2.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2.configure(highlightcolor="black")
        self.Radiobutton2.configure(justify='left')
        self.Radiobutton2.configure(text='''Female''')
        self.Radiobutton2.configure(variable=placement_support.selectedButton)
        self.Radiobutton2.configure(variable=self.var, value=2, command=self.femaleselect)

        self.Frame2 = tk.Frame(top)
        self.Frame2.place(relx=0.034, rely=0.351, relheight=0.196
                , relwidth=0.922)
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#d9d9d9")

        self.Label8 = tk.Label(self.Frame2)
        self.Label8.place(relx=0.404, rely=0.067, height=21, width=91)
        self.Label8.configure(background="#d9d9d9")
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(font=font10)
        self.Label8.configure(foreground="#000000")
        self.Label8.configure(text='''Company Detail''')

        self.Label9 = tk.Label(self.Frame2)
        self.Label9.place(relx=0.128, rely=0.276, height=20, width=94)
        self.Label9.configure(background="#d9d9d9")
        self.Label9.configure(disabledforeground="#a3a3a3")
        self.Label9.configure(foreground="#000000")
        self.Label9.configure(text='''Company Name''')

        self.Label10 = tk.Label(self.Frame2)
        self.Label10.place(relx=0.11, rely=0.485, height=20, width=74)
        self.Label10.configure(background="#d9d9d9")
        self.Label10.configure(disabledforeground="#a3a3a3")
        self.Label10.configure(foreground="#000000")
        self.Label10.configure(text='''Location''')

        self.Label11 = tk.Label(self.Frame2)
        self.Label11.place(relx=0.128, rely=0.694, height=20, width=54)
        self.Label11.configure(background="#d9d9d9")
        self.Label11.configure(cursor="fleur")
        self.Label11.configure(disabledforeground="#a3a3a3")
        self.Label11.configure(foreground="#000000")
        self.Label11.configure(text='''Package''')

        self.Text6 = tk.Text(self.Frame2)
        self.Text6.place(relx=0.33, rely=0.276, relheight=0.172, relwidth=0.466)
        self.Text6.configure(background="white")
        self.Text6.configure(font="TkTextFont")
        self.Text6.configure(foreground="black")
        self.Text6.configure(highlightbackground="#d9d9d9")
        self.Text6.configure(highlightcolor="black")
        self.Text6.configure(insertbackground="black")
        self.Text6.configure(selectbackground="blue")
        self.Text6.configure(selectforeground="white")
        self.Text6.configure(wrap="word")

        self.Text7 = tk.Text(self.Frame2)
        self.Text7.place(relx=0.33, rely=0.485, relheight=0.172, relwidth=0.466)
        self.Text7.configure(background="white")
        self.Text7.configure(font="TkTextFont")
        self.Text7.configure(foreground="black")
        self.Text7.configure(highlightbackground="#d9d9d9")
        self.Text7.configure(highlightcolor="black")
        self.Text7.configure(insertbackground="black")
        self.Text7.configure(selectbackground="blue")
        self.Text7.configure(selectforeground="white")
        self.Text7.configure(wrap="word")

        self.Text8 = tk.Text(self.Frame2)
        self.Text8.place(relx=0.33, rely=0.694, relheight=0.164, relwidth=0.466)
        self.Text8.configure(background="white")
        self.Text8.configure(font="TkTextFont")
        self.Text8.configure(foreground="black")
        self.Text8.configure(highlightbackground="#d9d9d9")
        self.Text8.configure(highlightcolor="black")
        self.Text8.configure(insertbackground="black")
        self.Text8.configure(selectbackground="blue")
        self.Text8.configure(selectforeground="white")
        self.Text8.configure(wrap="word")

        self.Label12 = tk.Label(self.Frame2)
        self.Label12.place(relx=0.807, rely=0.694, height=20, width=54)
        self.Label12.configure(background="#d9d9d9")
        self.Label12.configure(disabledforeground="#a3a3a3")
        self.Label12.configure(foreground="#000000")
        self.Label12.configure(text='''in Lakhs''')

        self.Frame4 = tk.Frame(top)
        self.Frame4.place(relx=0.034, rely=0.542, relheight=0.154
                , relwidth=0.922)
        self.Frame4.configure(relief='groove')
        self.Frame4.configure(borderwidth="2")
        self.Frame4.configure(relief="groove")
        self.Frame4.configure(background="#d9d9d9")

        self.Label13 = tk.Label(self.Frame4)
        self.Label13.place(relx=0.018, rely=0.095, height=21, width=44)
        self.Label13.configure(background="#d9d9d9")
        self.Label13.configure(disabledforeground="#a3a3a3")
        self.Label13.configure(font=font9)
        self.Label13.configure(foreground="#000000")
        self.Label13.configure(text='''Show :''')

        self.Label14 = tk.Label(self.Frame4)
        self.Label14.place(relx=0.018, rely=0.381, height=21, width=53)
        self.Label14.configure(background="#d9d9d9")
        self.Label14.configure(disabledforeground="#a3a3a3")
        self.Label14.configure(font=font9)
        self.Label14.configure(foreground="#000000")
        self.Label14.configure(text='''Update :''')

        self.Label15 = tk.Label(self.Frame4)
        self.Label15.place(relx=0.018, rely=0.667, height=21, width=34)
        self.Label15.configure(background="#d9d9d9")
        self.Label15.configure(disabledforeground="#a3a3a3")
        self.Label15.configure(font=font9)
        self.Label15.configure(foreground="#000000")
        self.Label15.configure(text='''Add :''')

        self.Button1 = tk.Button(self.Frame4)
        self.Button1.place(relx=0.128, rely=0.095, height=24, width=52)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(command=self.showstudent, text='''Student''')

        self.Button2 = tk.Button(self.Frame4)
        self.Button2.place(relx=0.257, rely=0.095, height=24, width=63)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(command=self.showcompany,text='''Company''')

        self.Button3 = tk.Button(self.Frame4)
        self.Button3.place(relx=0.404, rely=0.095, height=24, width=125)
        self.Button3.configure(activebackground="#ececec")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(command=self.showplace, text='''Placed company wise''')

        self.Label16 = tk.Label(self.Frame4)
        self.Label16.place(relx=0.679, rely=0.095, height=21, width=44)
        self.Label16.configure(background="#d9d9d9")
        self.Label16.configure(disabledforeground="#a3a3a3")
        self.Label16.configure(font=font9)
        self.Label16.configure(foreground="#000000")
        self.Label16.configure(text='''Delete :''')

        self.Button4 = tk.Button(self.Frame4)
        self.Button4.place(relx=0.771, rely=0.095, height=24, width=52)
        self.Button4.configure(activebackground="#ececec")
        self.Button4.configure(activeforeground="#000000")
        self.Button4.configure(background="#d9d9d9")
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(foreground="#000000")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(pady="0")
        self.Button4.configure(command=self.deletestudent, text='''Student''')

        self.Button5 = tk.Button(self.Frame4)
        self.Button5.place(relx=0.128, rely=0.381, height=24, width=143)
        self.Button5.configure(activebackground="#ececec")
        self.Button5.configure(activeforeground="#000000")
        self.Button5.configure(background="#d9d9d9")
        self.Button5.configure(disabledforeground="#a3a3a3")
        self.Button5.configure(foreground="#000000")
        self.Button5.configure(highlightbackground="#d9d9d9")
        self.Button5.configure(highlightcolor="black")
        self.Button5.configure(pady="0")
        self.Button5.configure(command=self.updatestuplace, text='''Student placed company''')

        self.Button6 = tk.Button(self.Frame4)
        self.Button6.place(relx=0.422, rely=0.381, height=24, width=76)
        self.Button6.configure(activebackground="#ececec")
        self.Button6.configure(activeforeground="#000000")
        self.Button6.configure(background="#d9d9d9")
        self.Button6.configure(disabledforeground="#a3a3a3")
        self.Button6.configure(foreground="#000000")
        self.Button6.configure(highlightbackground="#d9d9d9")
        self.Button6.configure(highlightcolor="black")
        self.Button6.configure(pady="0")
        self.Button6.configure(command=self.updatestuinfo, text='''Student Info''')

        self.Button7 = tk.Button(self.Frame4)
        self.Button7.place(relx=0.128, rely=0.667, height=24, width=52)
        self.Button7.configure(activebackground="#ececec")
        self.Button7.configure(activeforeground="#000000")
        self.Button7.configure(background="#d9d9d9")
        self.Button7.configure(disabledforeground="#a3a3a3")
        self.Button7.configure(foreground="#000000")
        self.Button7.configure(highlightbackground="#d9d9d9")
        self.Button7.configure(highlightcolor="black")
        self.Button7.configure(pady="0")
        self.Button7.configure(command=self.addstudent, text='''Student''')

        self.Button8 = tk.Button(self.Frame4)
        self.Button8.place(relx=0.257, rely=0.667, height=24, width=63)
        self.Button8.configure(activebackground="#ececec")
        self.Button8.configure(activeforeground="#000000")
        self.Button8.configure(background="#d9d9d9")
        self.Button8.configure(disabledforeground="#a3a3a3")
        self.Button8.configure(foreground="#000000")
        self.Button8.configure(highlightbackground="#d9d9d9")
        self.Button8.configure(highlightcolor="black")
        self.Button8.configure(pady="0")
        self.Button8.configure(command=self.addcompany, text='''Company''')

        self.Listbox1 = tk.Listbox(top)
        self.Listbox1.place(relx=0.034, rely=0.703, relheight=0.28
                , relwidth=0.92)
        self.Listbox1.configure(background="white")
        self.Listbox1.configure(disabledforeground="#a3a3a3")
        self.Listbox1.configure(font="TkFixedFont")
        self.Listbox1.configure(foreground="#000000")

if __name__ == '__main__':
    vp_start_gui()





